# estimate the pose of target objects detected
import numpy as np
import json
import os
import ast
import cv2
from YOLO.detector import Detector


# list of target fruits and vegs types
# Make sure the names are the same as the ones used in your YOLO model
TARGET_TYPES = ['orange', 'lemon', 'pear', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']


def estimate_pose(camera_matrix, obj_info, robot_pose):
    """
    function:
        estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
    input:
        camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
            |f_x, s,   c_x|
            |0,   f_y, c_y|
            |0,   0,   1  |
            (f_x, f_y): focal length in pixels
            (c_x, c_y): optical centre in pixels
            s: skew coefficient (should be 0 for PenguinPi)
        obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
        robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
    output:
        target_pose: dict, prediction of target pose
    """
    # read intrinsics
    # camera_matrix expected as 3x3: [[fx, s, cx],[0, fy, cy],[0,0,1]]
    fx = float(camera_matrix[0][0])
    fy = float(camera_matrix[1][1])
    cx = float(camera_matrix[0][2])
    # there are 8 possible types of fruits and vegs
    # Measurements provided by the user (width, depth, height) in metres
    target_dimensions_dict = {
        'orange': [0.084, 0.085, 0.077],
        'lemon': [0.074, 0.047, 0.05],
        'pear': [0.0748, 0.0671, 0.11],  # pear height doesn't include the stem
        'tomato': [0.074, 0.074, 0.064],
        'capsicum': [0.079, 0.08, 0.09],
        'potato': [0.093, 0.073, 0.054],
        'pumpkin': [0.085, 0.082, 0.075],
        'garlic': [0.063, 0.06, 0.075]
    }

    # parse detection info
    target_class = obj_info[0]
    target_box = obj_info[1]  # expected [x_center, y_center, width, height] in pixels

    if target_class not in target_dimensions_dict:
        # unknown class, cannot estimate
        return None

    true_height = float(target_dimensions_dict[target_class][2])

    # ensure numpy array to index correctly
    box = np.asarray(target_box, dtype=float).ravel()
    pixel_cx = float(box[0])    # x center in pixels
    pixel_h = float(box[3])     # box height in pixels

    if pixel_h <= 0:
        return None

    # estimate depth (z) using pinhole camera model: depth = (real_height * fy) / pixel_height
    depth = (true_height * fy) / pixel_h

    # compute lateral offset in camera frame (x to right is positive)
    x_cam = (pixel_cx - cx) * depth / fx

    # camera frame: forward = depth (z), right = x_cam
    forward = depth
    lateral = x_cam

    # convert to world frame using robot_pose = [x, y, theta]
    rob_x = float(robot_pose[0][0]) if hasattr(robot_pose[0], '__len__') else float(robot_pose[0])
    rob_y = float(robot_pose[1][0]) if hasattr(robot_pose[1], '__len__') else float(robot_pose[1])
    rob_theta = float(robot_pose[2][0]) if hasattr(robot_pose[2], '__len__') else float(robot_pose[2])

    # delta in world frame
    delta_x_world = forward * np.cos(rob_theta) - lateral * np.sin(rob_theta)
    delta_y_world = forward * np.sin(rob_theta) + lateral * np.cos(rob_theta)

    target_pose = {'x': rob_x + delta_x_world, 'y': rob_y + delta_y_world}

    return target_pose


def merge_estimations(target_pose_dict):
    """
    function:
        merge estimations of the same target
    input:
        target_pose_dict: dict, generated by estimate_pose
    output:
        target_est: dict, target pose estimations after merging
    """
    target_est = {}

    # Greedy spatial clustering per class using a distance threshold.
    # Observations for a class are grouped if they are within `merge_threshold` metres of a cluster centre.
    merge_threshold = 0.15  # 15 cm (as specified in lab notes)

    # organize estimates by class base name (strip trailing _index)
    per_class = {}
    for k, pose in target_pose_dict.items():
        if pose is None:
            continue
        # key format expected like 'orange_0' or similar
        cls = k.split('_')[0].lower()
        per_class.setdefault(cls, []).append((k, pose))

    for cls, items in per_class.items():
        clusters = []  # each cluster: {'count':int, 'sum_x':float, 'sum_y':float}
        for name, pose in items:
            x = float(pose['x'])
            y = float(pose['y'])
            placed = False
            for c in clusters:
                cx = c['sum_x'] / c['count']
                cy = c['sum_y'] / c['count']
                dist = np.hypot(x - cx, y - cy)
                if dist <= merge_threshold:
                    c['sum_x'] += x
                    c['sum_y'] += y
                    c['count'] += 1
                    placed = True
                    break
            if not placed:
                clusters.append({'sum_x': x, 'sum_y': y, 'count': 1})

        # output cluster centres as final estimates
        for i, c in enumerate(clusters):
            cx = c['sum_x'] / c['count']
            cy = c['sum_y'] / c['count']
            key = f"{cls}_{i}"
            target_est[key] = {'x': cx, 'y': cy}

    return target_est


# main loop
if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)

    # read in camera matrix
    fileK = f'{script_dir}/calibration/param/intrinsic.txt'
    camera_matrix = np.loadtxt(fileK, delimiter=',')

    # init YOLO model
    model_path = f'{script_dir}/YOLO/model/yolov8_model.pt'
    yolo = Detector(model_path)

    # create a dictionary of all the saved images with their corresponding robot pose
    image_poses = {}
    with open(f'{script_dir}/lab_output/images.txt') as fp:
        for line in fp.readlines():
            pose_dict = ast.literal_eval(line)
            image_poses[pose_dict['imgfname']] = pose_dict['pose']

    # estimate pose of targets in each image
    target_pose_dict = {}
    detected_type_list = []
    for image_path in image_poses.keys():
        input_image = cv2.imread(image_path)
        bounding_boxes, bbox_img = yolo.detect_single_image(input_image)
        # cv2.imshow('bbox', bbox_img)
        # cv2.waitKey(0)
        robot_pose = image_poses[image_path]

        for detection in bounding_boxes:
            # count the occurrence of each target type
            occurrence = detected_type_list.count(detection[0])
            target_pose_dict[f'{detection[0]}_{occurrence}'] = estimate_pose(camera_matrix, detection, robot_pose)

            detected_type_list.append(detection[0])

    # merge the estimations of the targets so that there are at most 3 estimations of each target type
    target_est = {}
    target_est = merge_estimations(target_pose_dict)
    print(target_est)
    # save target pose estimations
    with open(f'{script_dir}/lab_output/targets.txt', 'w') as fo:
        json.dump(target_est, fo, indent=4)

    print('Estimations saved!')
